import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// ❗ This file is a Server Component, so you can't use hooks here directly

import LayoutSelector from './components/LayoutSelector'; // use client wrapper

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LayoutSelector>{children}</LayoutSelector>
      </body>
    </html>
  );
}
