ALTER TABLE C_ACCOUNT
ADD COLUMN PHONE VARCHAR(20) NULL AFTER EMAIL,
ADD COLUMN MOBILE VARCHAR(20) NULL AFTER PHONE,
ADD COLUMN WEBSITE VARCHAR(255) NULL AFTER MOBILE,
ADD COLUMN EIN VARCHAR(20) NULL AFTER WEBSITE,
ADD COLUMN DUNS_NUMBER VARCHAR(20) NULL AFTER EIN,
ADD COLUMN LINKEDIN VARCHAR(255) NULL AFTER DUNS_NUMBER,
ADD COLUMN YOUTUBE VARCHAR(255) NULL AFTER LINKEDIN,
ADD COLUMN FACEBOOK VARCHAR(255) NULL AFTER YOUTUBE,
ADD COLUMN TWITTER VARCHAR(255) NULL AFTER FACEBOOK,
ADD COLUMN INSTAGRAM VARCHAR(255) NULL AFTER TWITTER,
ADD COLUMN COMPANY_SIZE VARCHAR(20) NULL AFTER INSTAGRAM,
ADD COLUMN LOYALTY_STATUS VARCHAR(20) NULL AFTER COMPANY_SIZE;

INSERT INTO C_GENERIC_NAMES (g_id, Name, category, child_gid, single_value, active, description)
VALUES (41, 'Company Size', 'account', NULL, NULL, 1, 'Size of the company by employee count');

INSERT INTO C_GENERIC_NAMES (g_id, Name, category, child_gid, single_value, active, description)
VALUES (42, 'Loyalty Status', 'account', NULL, NULL, 1, 'Customer loyalty status tier');
